global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rag-api'
    static_configs:
      # host.docker.internal permite conectar desde Docker a tu localhost de Windows
      - targets: ['host.docker.internal:8000'] 
    metrics_path: '/metrics'